### ISSUE TITLE
Automatically create new issues on the t2-cli repo

### ISSUE THREAD

**Issue by johnnyman727** [tessel/t2-crash-reporter#15]
It would be really useful if the crash reporter would automatically post new issues to the t2-cli repo when there is a crash with the CLI. If we could also get additional comments when further thresholds are hit (there have been 10 instances of this crash in the last hour, etc.) that would be great for determining the severity.

**Comment by tikurahul** [comment]
This is a great idea, and this is what I was thinking:

## Features
- Crash reports will also track a GitHub issue number.
- They (Github issue numbers) will become a searchable property, as the model is exposed via the search index as well.
- Updates to the issue via comments on repeated instances of crashes.
- Wire the Github issue close web hook to mark the crash resolved (which will clean up Trending Crashes automatically).

## Global Hooks
- The ability to turn off Github integration completely, in case of issues or if there is too much noise). 

Does that sound good?
If you have other ideas, or feature requests please let me know.

**Comment by johnnyman727** [comment]
Sounds great to me!

**Comment by tikurahul** [comment]
Great. Already done with Features 1, 2.

Working on the GitHub hooks right now. I will give everyone a heads up when we start testing this end to end. There are issues that are going to be automatically created. 😄

**Comment by tikurahul** [comment]
With this, we have GitHub web hooks support for resolving issues. Several other improvements.
https://github.com/tessel/t2-crash-reporter/pull/19

**Comment by tikurahul** [comment]
Complete !

🏆
