### ISSUE TITLE
Needs newline after triple-tick fence

### ISSUE THREAD

**Issue by rwaldron** [tessel/t2-crash-reporter#30]
Presently, stack trace output looks like this: 

![](https://i.gyazo.com/117153fbf88be8331f451522bdd99cf4.png)

Because there is no newline after the "```": 

![](https://i.gyazo.com/e456307dc4600a821afe813abcba99cb.png)

When that is added, the output looks like this: 

![](https://i.gyazo.com/1b5027d6029375d36806528252841c75.png)

**Comment by Frijol** [comment]
duplicate of https://github.com/tessel/t2-crash-reporter/issues/27 and fixed in https://github.com/tessel/t2-crash-reporter/pull/28 but awaiting deployment (I don't know how to do it)

**Comment by rwaldron** [comment]
Oops, sorry for the dup. Closing!

**Comment by tikurahul** [comment]
This patch has been deployed. 👍 

Will update the Readme with instructions on how to deploy the codebase.
